name: GsAL
favicon: null
layout_spectrum: 0.6386609426699579
typography_spectrum: 0.6157546225003898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005a36'
    - '#6d9750'
    - '#000000'
    - '#ffc20e'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
