name: GsAL
favicon: null
layout_spectrum: 0.6386609426699579
typography_spectrum: 0.6157546225003898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9872992658056319
  lightness: 0.9522940586321056
  saturation: 0.5734129254706204
  rhythmicContrast: 0.9900748485233635
purpose: []
