typography_spectrum: 0.26437721168622375
color:
  brandColors:
    - '#005A36'
    - '#6D9750'
    - '#000000'
    - '#FFC20E'
    - '#FFFFFF'
  brandStrength: 0.915321976179257
  lightness: 0.17911525932140648
  saturation: 0.5630396935157478
  rhythmicContrast: 0.553343779174611
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9308009236119688
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: David Saah
  email: dssaah@usfca.edu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed14f4d4-734b-4b01-a8d8-13d905a61fef.png
name: GsAL
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: GsAL Info
    url: 'http://usfca.edu/gsal'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50652386-3641-4b6d-8a7d-f1f84f46f978.png
title: Geospatial Analysis Lab
description: University of San Francisco
purpose: []
